# Generated by Django 5.1.4 on 2024-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('quantity_people', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
